POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Example",
    "number": "509-34567809"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Example"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "509-34567809"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{

}